name: Cypress typescript Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Cypress Test
      uses: cypress-io/github-action@v6