name: End-to-end tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run

      - name: Generate Allure Report
        run: npm run allure:report

      - name: Ensure Allure Report Directory Exists
        run: mkdir -p allure-cypress-cucumber-master-medic-clinic/allure-report

      - name: Copy Allure Report
        run: cp -R allure-report/* allure-cypress-cucumber-master-medic-clinic/allure-report/

      - name: List Files for Debugging
        run: |
          echo "Listing files in allure-cypress-cucumber-master-medic-clinic/allure-report"
          ls -R allure-cypress-cucumber-master-medic-clinic/allure-report

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-cypress-cucumber-master-medic-clinic/allure-report